### PR TITLE
Workaround disallow changes by splitting configuration file setup

### PR DESCRIPTION
**Pull request by alexvanyo**
This adds a potential workaround for #135 by taking advantage of the configuration split for `disableTestProguardFiles`.

I don't think the main configuration has to wait for `afterEvaluate` - it wasn't in `afterEvaluate` [prior to](https://github.com/slackhq/keeper/pull/117/files#diff-97986db993489fce0231211149a4abef24deae6c53cea6f6e422434faaebc849L281) #117, so maybe we can move that part out of `afterEvaluate` to avoid running into the `disallowChanges` issue.

If `disableTestProguardFiles` is not `true`, then the new `disallowChanges()` will still cause the #135 issue, but on the latest AGP versions not specifying `disableTestProguardFiles` won't work anyway.

I validated this change locally against https://github.com/alexvanyo/composelife/pull/1500 updating `8.4.0-alpha04` to `8.4.0-alpha11`.

### CODE REVIEW

**Review by ZacSweers — APPROVED** [review]

**Comment by ZacSweers** [comment]
Thanks! Sorry for the delay, I didn't see this

**Comment by carlonzo** [comment]
any plans on getting this one released anytime soon? or are there snapshots we can use to test the fix?

**Comment by iliaskomp** [comment]
It would also be really great for us if we there would be a release with this fix, thanks!

**Comment by ZacSweers** [comment]
The fix no longer appears to work https://github.com/slackhq/keeper/pull/141. Sorry but I'm not sure what can be done about it at this point. In the meantime, please be respectful of OSS maintainers and don't nag for releases of something you could build yourself: https://www.zacsweers.dev/you-are-not-blocked/

**Pull request merged**
